/// An item on the user's shopping list.
///
/// Items are generated by the AI planner endpoint and represent ingredients
/// that are missing (or in short supply) for the user's planned meals.
class ShoppingListItem {
  const ShoppingListItem({
    required this.name,
    required this.neededForMeals,
    required this.unit,
    required this.suggestedQuantity,
  });

  /// Lower-cased, trimmed ingredient name.
  final String name;

  /// Number of planned meals that need this item.
  ///
  /// In the legacy endpoint this came from the server; the AI endpoint does
  /// not currently return a per-meal breakdown so this defaults to 1.
  final int neededForMeals;

  /// Unit of measurement (e.g. "g", "ml", "pcs").
  final String unit;

  /// Suggested purchase quantity.
  final double suggestedQuantity;

  /// Creates from the legacy shopping endpoint response format.
  factory ShoppingListItem.fromMap(Map<String, dynamic> map) {
    return ShoppingListItem(
      name: (map['name'] as String? ?? '').trim().toLowerCase(),
      neededForMeals: (map['needed_for_meals'] as num?)?.toInt() ?? 0,
      unit: (map['unit'] as String? ?? 'pcs').trim().toLowerCase(),
      suggestedQuantity: (map['suggested_quantity'] as num?)?.toDouble() ?? 1.0,
    );
  }

  /// Creates from the AI planner shopping-gap item format.
  ///
  /// The AI endpoint returns items with fields:
  /// - `normalized_name`   → [name]
  /// - `suggested_quantity` → [suggestedQuantity]
  /// - `suggested_unit`     → [unit]
  /// - `reason` / `confidence` (not mapped here; available for future use)
  factory ShoppingListItem.fromAiMap(Map<String, dynamic> map) {
    return ShoppingListItem(
      name: (map['normalized_name'] as String? ?? '').trim().toLowerCase(),
      neededForMeals: 1,
      unit: (map['suggested_unit'] as String? ?? 'pcs').trim().toLowerCase(),
      suggestedQuantity:
          (map['suggested_quantity'] as num?)?.toDouble() ?? 1.0,
    );
  }
}
