import '../api/api_client.dart';
import '../models/recommendations.dart';

class RecommendationRepository {
  RecommendationRepository(this._apiClient);

  final ApiClient _apiClient;

  Future<PlannerRecommendations> fetchPlannerRecommendations() async {
    final response = await _apiClient.getObject(
      '/api/v1/recommendations/planner',
    );
    return PlannerRecommendations.fromMap(response);
  }

  Future<DashboardRecommendations> fetchDashboardRecommendations() async {
    final response = await _apiClient.getObject(
      '/api/v1/recommendations/dashboard',
    );
    return DashboardRecommendations.fromMap(response);
  }

  /// Fetches pantry-aware substitution hints for a list of ingredient names.
  ///
  /// Returns a map of [ingredient] → [SubstitutionHint] for convenient UI
  /// look-up. Each hint includes a text description and any pantry items that
  /// are known substitutes and are currently in the user's pantry.
  Future<Map<String, SubstitutionHint>> fetchSubstitutionHints(
    List<String> ingredients,
  ) async {
    if (ingredients.isEmpty) {
      return const <String, SubstitutionHint>{};
    }

    final response = await _apiClient.getObject(
      '/api/v1/substitutions',
      queryParameters: <String, String>{'ingredients': ingredients.join(',')},
    );

    final hintsList = (response['hints'] as List<dynamic>? ?? const <dynamic>[])
        .whereType<Map>()
        .map((item) => SubstitutionHint.fromMap(item.cast<String, dynamic>()))
        .toList(growable: false);

    return <String, SubstitutionHint>{
      for (final hint in hintsList) hint.ingredient: hint,
    };
  }

  /// Fetches AI-generated pantry coverage for [recipeId].
  ///
  /// Calls the AI planner endpoint which returns per-ingredient detail
  /// (status, quantities, confidence, optional substitution) generated by
  /// Gemini and validated by the backend's rule-based checks.
  ///
  /// Falls back to deriving [availableIngredients] / [missingIngredients]
  /// convenience lists from the AI payload so existing coverage UI works
  /// without changes.
  Future<PantryCoverage> fetchPantryCoverage(String recipeId) async {
    final response = await _apiClient.getObject(
      '/api/v1/ai/planner/coverage/$recipeId',
    );

    // The AI endpoint wraps the payload in a top-level envelope:
    // { "payload": { ... }, "validation": { "valid": true, "issues": [] } }
    final payload =
        (response['payload'] as Map<String, dynamic>?) ??
        response;

    return PantryCoverage.fromAiPayload(payload);
  }
}
